// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC95LrIWFLHdAOhqT_VEhCe5XRGeHjISCc',
    appId: '1:1009977286740:web:5eab8044fe857facc64dc1',
    messagingSenderId: '1009977286740',
    projectId: 'cosmetics-ecommerce-16305',
    authDomain: 'cosmetics-ecommerce-16305.firebaseapp.com',
    storageBucket: 'cosmetics-ecommerce-16305.firebasestorage.app',
    measurementId: 'G-QJLK2VSY8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp7HCtrEx-DMjZuJ-tzMAGykvuNMeXSRw',
    appId: '1:1009977286740:android:49986f027f416c62c64dc1',
    messagingSenderId: '1009977286740',
    projectId: 'cosmetics-ecommerce-16305',
    storageBucket: 'cosmetics-ecommerce-16305.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWliS0InpOXI2HKAVA5Xd0flwz35MSKGU',
    appId: '1:1009977286740:ios:a70dc45728c3a5a9c64dc1',
    messagingSenderId: '1009977286740',
    projectId: 'cosmetics-ecommerce-16305',
    storageBucket: 'cosmetics-ecommerce-16305.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWliS0InpOXI2HKAVA5Xd0flwz35MSKGU',
    appId: '1:1009977286740:ios:a70dc45728c3a5a9c64dc1',
    messagingSenderId: '1009977286740',
    projectId: 'cosmetics-ecommerce-16305',
    storageBucket: 'cosmetics-ecommerce-16305.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC95LrIWFLHdAOhqT_VEhCe5XRGeHjISCc',
    appId: '1:1009977286740:web:f87471a2a8b29ac6c64dc1',
    messagingSenderId: '1009977286740',
    projectId: 'cosmetics-ecommerce-16305',
    authDomain: 'cosmetics-ecommerce-16305.firebaseapp.com',
    storageBucket: 'cosmetics-ecommerce-16305.firebasestorage.app',
    measurementId: 'G-0TPCQKM86C',
  );
}
